In [1]:
import numpy as np
import numpy.linalg as nl
import fractions
np.set_printoptions(formatter={'all':lambda x: 
                               str(fractions.Fraction(x).limit_denominator())})

In [2]:
def linear_equation(coefficients_matrix, result_vector):
    coefficients = np.array(coefficients_matrix)
    results = result_vector
    solve = np.linalg.solve(coefficients, results)
    correct = np.allclose(np.dot(coefficients, solve), results)
    return solve, correct

In [3]:
linear_equation([[1,1,2],[0,1,0],[0,0,1]], [[1],[1],[1]])

(array([[-2],
        [1],
        [1]]), True)

In [4]:
linear_equation([[4,6,2],[3,4,1],[2,8,13]], [[9],[7],[2]])

(array([[3],
        [-1/2],
        [0]]), True)

In [5]:
A = [[1, 1, 1],
     [3, 2, 1],
     [2, 1, 2]]

s = [15, 28, 23]

In [6]:
linear_equation(A, s)

(array([3, 7, 5]), True)

In [8]:
nl.inv(A)

array([[-3/2, 1/2, 1/2],
       [2, 0, -1],
       [1/2, -1/2, 1/2]])

In [9]:
np.dot(A, nl.inv(A))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])