In [1]:
import numpy as np
import fractions

In [10]:
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [11]:
def linear_equation(coefficients_matrix, result_vector):
    coefficients = np.array(coefficients_matrix)
    results = result_vector
    solve = np.linalg.solve(coefficients, results)
    correct = np.allclose(np.dot(coefficients, solve), results)
    return solve, correct

In [12]:
linear_equation([[3,1], [1,2]], [9,8])

(array([2, 3]), True)

In [13]:
linear_equation([[3,2], [2,3]], [7,8])

(array([1, 2]), True)

In [14]:
linear_equation([[9, -17], [ -13, 7]], [ -20, -94])

(array([11, 7]), True)

In [15]:
linear_equation([[5, -2], [4, 5]], [ -13, -6])

(array([-7/3, 2/3]), True)

In [16]:
linear_equation([[5, 7], [20, -18]], [11, 39])

(array([471/230, 5/46]), True)

In [18]:
linear_equation([[3, -2, 1], [1,1,1], [3,-2,-1]], [7, 2, 3])

(array([1, -1, 2]), True)