In [1]:
import numpy as np

In [2]:
a = np.array([[2, 3], [10, 1]])
b = np.array([[0], [1]])
np.dot(a,b)

array([[3],
       [1]])

In [3]:
a = np.array([[2,3], [10, 1]])
b = np.array([[1], [0]])
np.dot(a,b)

array([[ 2],
       [10]])

In [4]:
a = np.array([[7, -6], [12, 8]])
b = np.array([[5], [6]])
np.dot(a,b)

array([[ -1],
       [108]])

In [5]:
np.dot([[0,1], [-1, 0]], [[1,1], [0,1]])

array([[ 0,  1],
       [-1, -1]])

# Quizz

In [8]:
import numpy.linalg as nl
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [9]:
r = np.array([[3], [2]])

In [10]:
A = np.array([[1/2, -1], [0, 3/4]])

In [11]:
np.dot(A, r)

array([[-1/2],
       [3/2]])

In [13]:
np.dot(A, [[-2], [4]])

array([[-5],
       [3]])

In [14]:
M = [[-1/2, 1/2], [1/2, 1/2]]

In [15]:
np.dot(M, [[1], [0]])

array([[-1/2],
       [1/2]])

In [16]:
np.dot(M, [[0], [1]])

array([[1/2],
       [1/2]])

In [17]:
np.dot(M, r)

array([[-1/2],
       [5/2]])

In [18]:
np.dot([[1,0], [0, 8]], [[1, 0], [-1/2, 1]])

array([[1, 0],
       [-4, 8]])