In [1]:
import sympy as sp
import numpy as np
import numpy.linalg as nl
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [2]:
sp.init_printing(use_latex='mathjax')

# Characteristic polynomial

for a 2x2 the formula is:

l**2 - ((a + d) * l) + (a * d - b * c)

In [3]:
def reduce(matrix):
    matrix = np.array(matrix)
    a = matrix[0,0]
    b = matrix[0,1]
    c = matrix[1,0]
    d = matrix[1,1]
    l = sp.symbols('l')
    expr = l**2 - ((a + d) * l) + (a * d - b * c)
    expr = sp.simplify(expr)
    return expr

In [4]:
def testEigenVector(matrix, lambda1, lambda2, *testVectors):
    result = []
    for vector in testVectors:
        vector = np.array(vector)
        dotP = np.dot(matrix, vector)
        for l in [lambda1, lambda2]:
            dotL = int(l) * vector
            if np.allclose(dotP, dotL):
               result.append(vector)
    
    return result

# New Matrix

In [5]:
A = [[1,0], [0,2]]

In [6]:
expr = reduce(A)
expr

 2          
l  - 3⋅l + 2

In [7]:
solutions = sp.solve(expr)
solutions

[1, 2]

In [8]:
eigenvalues, eigenvectors = nl.eig(A)
eigenvectors

array([[1, 0],
       [0, 1]])

In [9]:
testEigenVector(A, solutions[0], solutions[1], [0, 2], [1, -1], [0, 3], [1,0])

[array([0, 2]), array([0, 3]), array([1, 0])]

# New Matrix

In [10]:
A = [[3,4], [0,5]]

In [11]:
expr = reduce(A)
expr

 2           
l  - 8⋅l + 15

In [12]:
solutions = sp.solve(expr)
solutions

[3, 5]

In [13]:
eigenvalues, eigenvectors = nl.eig(A)
eigenvectors

array([[1, 832040/930249],
       [0, 416020/930249]])

In [14]:
testEigenVector(A, solutions[0], solutions[1], [-1, -1/2], [0,0], [2,1], [3,0])

[array([-1, -1/2]), array([0, 0]), array([0, 0]), array([2, 1]), array([3, 0])]

# New Matrix

In [15]:
A = [[1,0],[-1,4]]

In [16]:
expr = reduce(A)
expr

 2          
l  - 5⋅l + 4

In [17]:
solutions = sp.solve(expr)
solutions

[1, 4]

In [18]:
eigenvalues, eigenvectors = nl.eig(A)
eigenvectors

array([[0, 932975/983442],
       [1, 275423/870964]])

In [19]:
testEigenVector(A, solutions[0], solutions[1], [0, 1], [3,2], [3,1], [3,-1])

[array([0, 1]), array([3, 1])]

# New Matrix

In [20]:
A = [[-3, 8], [2, 3]]

In [21]:
expr = reduce(A)
expr

 2     
l  - 25

In [22]:
solutions = sp.solve(expr)
solutions

[-5, 5]

In [23]:
eigenvalues, eigenvectors = nl.eig(A)
eigenvectors

array([[-283009/291719, -470832/665857],
       [213329/879578, -470832/665857]])

In [24]:
testEigenVector(A, solutions[0], solutions[1], [0, 2], [-1, -1], [4,-1], [1,1])

[array([-1, -1]), array([4, -1]), array([1, 1])]

# New Matrix

In [25]:
A = [[5, 4], [-4, -3]]

In [26]:
expr = reduce(A)
expr

 2          
l  - 2⋅l + 1

In [27]:
solutions = sp.solve(expr)
solutions

[1]

# New Matrix

In [28]:
A = [[-2, -3], [1,1]]

In [29]:
expr = reduce(A)
expr

 2        
l  + l + 1

In [30]:
solutions = sp.solve(expr)
solutions

⎡  1   √3⋅ⅈ    1   √3⋅ⅈ⎤
⎢- ─ - ────, - ─ + ────⎥
⎣  2    2      2    2  ⎦

# New Matrix

In [31]:
A = [[3/2, -1], [-1/2, 1/2]]

In [32]:
expr = reduce(A)
expr

 2               
l  - 2.0⋅l + 0.25

# New Matrix

In [40]:
A = np.array([[3/2, -1], [-1/2, 1/2]])

In [41]:
expr = reduce(A)
expr

 2               
l  - 2.0⋅l + 0.25

In [42]:
solutions = sp.solve(expr)
solutions

[0.133974596215561, 1.86602540378444]

In [43]:
1 - np.sqrt(3) / 2

0.1339745962155614

In [44]:
1 + np.sqrt(3) / 2

1.8660254037844386

In [45]:
testEigenVector(
    A, 
    solutions[0], 
    solutions[1], 
    [-1-np.sqrt(3), 1], [-1+np.sqrt(3), 1], 
    [1-np.sqrt(5), 1], [1+np.sqrt(5), 1],
    [1-np.sqrt(3), 1], [1+np.sqrt(3), 1], 
    [-1-np.sqrt(5), 1], [-1+np.sqrt(5), 1])

[]

In [46]:
A @ A

array([[11/4, -2],
       [-1, 3/4]])