In [1]:
import numpy as np

In [2]:
np.dot([2,4,5,6], [[1],[3],[2],[1]])

array([30])

In [3]:
np.dot([[1],[3],[2],[1]], [[2,4,5,6]])

array([[ 2,  4,  5,  6],
       [ 6, 12, 15, 18],
       [ 4,  8, 10, 12],
       [ 2,  4,  5,  6]])

In [4]:
np.dot([[1,2,3], [4,0,1]], [[1,1,0], [0,1,1], [1,0,1]])

array([[4, 3, 5],
       [5, 4, 1]])

In [5]:
np.dot([[2,-1], [0,3], [1,0]], [[0,1,4,-1], [-2,0,0,2]])

array([[ 2,  2,  8, -4],
       [-6,  0,  0,  6],
       [ 0,  1,  4, -1]])

In [6]:
np.dot([[1,0], [0,1]], [[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
(1/2) * np.dot([[1, -1], [-1, 3]], [[5],[2]])

array([[1.5],
       [0.5]])

In [10]:
 np.dot([[3,-1], [-1, 1]], [[2,0],[4,2]]) * 1/2

array([[ 1., -1.],
       [ 1.,  1.]])