In [1]:
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [2]:
s = np.array([ [4/ 13], [-3/13], [-12/13]])
s

array([[4/13],
       [-3/13],
       [-12/13]])

In [3]:
r = np.array([[6], [2], [3]])
r

array([[6],
       [2],
       [3]])

In [7]:
A = np.array([[1,0, -s[0] / s[2]], [0, 1, - s[1] / s[2] ]])
A

array([[1, 0, 1/3],
       [0, 1, -1/4]])

In [8]:
np.dot(A, r)

array([[7],
       [5/4]])

In [10]:
R = np.array([[5,-1,-3,7], [4,-4,1,-2], [9,3,0,12]])
R

array([[5, -1, -3, 7],
       [4, -4, 1, -2],
       [9, 3, 0, 12]])

In [11]:
np.dot(A,R)

array([[8, 0, -3, 11],
       [7/4, -19/4, 1, -5]])