In [1]:
import numpy as np
import numpy.linalg as nl

In [2]:
A = np.array([[2,0], [0,2]])

In [3]:
A @ A @ A

array([[8, 0],
       [0, 8]])

Doing transformation T, n times: T\*\*n is 
for D the matrix such as CD = T and D is diagonal matrix:
then T\*\*n = C @ D\*\*n @ inv(C)

In [4]:
def getDiagonal(T, C):
    T = np.array(T)
    C = np.array(C)
    Cinv = nl.inv(C)
    return Cinv @ T @ C

In [5]:
T = np.array([[6,-1], [2,3]])

In [6]:
C = np.array([[1,1], [1,2]])

In [7]:
D = getDiagonal(T, C)
D

array([[5., 0.],
       [0., 4.]])

In [8]:
getDiagonal([[2,7],[0,-1]], [[7,1], [-3,0]])

array([[-1.00000000e+00,  0.00000000e+00],
       [ 1.77635684e-15,  2.00000000e+00]])

In [9]:
getDiagonal([[1,0], [2,-1]], [[1,0], [1,1]])

array([[ 1.,  0.],
       [ 0., -1.]])

In [10]:
C = np.array([[1, 2], [0,1]])

In [11]:
nl.inv(C)

array([[ 1., -2.],
       [ 0.,  1.]])

In [12]:
C @ np.array([[10, 0], [0, 10]]) @ nl.inv(C)

array([[10.,  0.],
       [ 0., 10.]])

In [13]:
T = np.array([[6, -1], [2,3]])

In [14]:
T @ T @ T

array([[186, -61],
       [122,   3]])

In [15]:
T = np.array([[2,7], [0 , -1]])

In [16]:
T @ T @ T

array([[ 8, 21],
       [ 0, -1]])

In [17]:
T = np.array([[1,0], [2,-1]])

In [18]:
T ** 5 # Does not work because T is a np.array

array([[ 1,  0],
       [32, -1]], dtype=int32)

In [19]:
T**5

array([[ 1,  0],
       [32, -1]], dtype=int32)

In [20]:
T @ T @ T @ T @ T

array([[ 1,  0],
       [ 2, -1]])

In [21]:
nl.matrix_power(T, 5)

array([[ 1,  0],
       [ 2, -1]])

In [22]:
T = np.matrix([[1,0], [2,-1]])

In [23]:
T ** 5 # T has to be a matrix for that to work

matrix([[ 1,  0],
        [ 2, -1]])