In [1]:
import numpy as np
import numpy.linalg as nl
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [2]:
def scalarProjection(a, b, withVector=False):
    a = np.array(a)
    b = np.array(b)
    scalar = np.dot(a,b) / np.dot(b,b)
    if withVector:
        return np.array(b) * scalar
    else:
        return scalar

In [3]:
ship = [1,2]
current = [1,1]
scalarProjection(ship, current, True)

array([3/2, 3/2])

In [4]:
ball = np.array([2, 1])
wind = np.array([3, -4])
nl.norm(scalarProjection(ball, wind, True))

0.4

In [5]:
def cosVector(a,b):
    return np.dot(a,b) / (nl.norm(a) * nl.norm(b))

In [6]:
def newCoordinate(a, *newVectors):
    assert len(a) == len(newVectors), "Shape and vectors not matching"
    results = []
    for index, dimension in enumerate(newVectors):
        for otherIndex in range(index + 1, len(newVectors)):
            assert cosVector(dimension, newVectors[otherIndex]) == 0, "Vector %d and %d not aligned" % (index, otherIndex)
        
        results.append(scalarProjection(a, dimension))
    return np.array(results)

In [7]:
newCoordinate([-4,-3,8], [1,2,3], [-2,1,0], [-3,-6,5])

array([1, 1, 1])

In [8]:
def isLinearIndependant(*vect):
    EPSILON = np.power(10.0, -15)
    d = np.row_stack(vect)
    
    # m < n (the number of vectors is greater than their length): 
    # they are linearly dependent (always).
    if d.shape[0] > d.shape[1]:
        return False
    
    sign, logdet = nl.slogdet(d)
    # A set of n vectors of length n is linearly independent 
    # if the matrix with these vectors as columns has a non-zero determinant. 
    return abs(np.exp(logdet)) >= EPSILON

In [9]:
isLinearIndependant([1,2,-1],[3,-4,5],[1,-8,7])

False

In [10]:
originPosition = np.array([3,2,4])
speed = np.array([-1,2,-3])
originPosition + 2 * speed

array([1, 6, -2])