In [1]:
import numpy as np
import numpy.linalg as nl

In [2]:
A = np.array([[1,2,5], [3,4,6],[7,8,9]])
A

array([[1, 2, 5],
       [3, 4, 6],
       [7, 8, 9]])

In [3]:
A.T

array([[1, 3, 7],
       [2, 4, 8],
       [5, 6, 9]])

In [4]:
nl.inv(A)

array([[  6. , -11. ,   4. ],
       [ -7.5,  13. ,  -4.5],
       [  2. ,  -3. ,   1. ]])

In [5]:
np.dot(nl.inv(A), A)

array([[ 1.00000000e+00,  3.55271368e-15,  0.00000000e+00],
       [-4.44089210e-15,  1.00000000e+00, -6.21724894e-15],
       [ 0.00000000e+00,  8.88178420e-16,  1.00000000e+00]])

# Note

othronormal if A.T == inv(A)

if orthonormal, np.dot(A.T, A) == np.dot(A, A.T)

# Build Orthonormal matrix

## Gram-Schmidt process

In [6]:
vectors = np.array([[2,4,6], [5,8,3], [8,3,2]])

In [7]:
def buildOrthonormalMatrixBasedOn(*vectors):
    vectors = np.array(vectors[0])
    print("Shape ", vectors.shape)
    numberOfVector, targetDimension = vectors.shape
    assert numberOfVector >= targetDimension, "You need more vectors"
    
    baseVectors = []
    
    for vectorIndex in range(targetDimension):
        currentVector = vectors[vectorIndex]
        delta = np.zeros((targetDimension))
        for v in range(0, vectorIndex):
            baseVector = baseVectors[v]
            delta = delta - (np.dot(currentVector, baseVector) * baseVector)
        
        tempVector = currentVector + delta
        baseVectors.append(tempVector / nl.norm(tempVector))

    # Check if all vectors are orthogonal
    EPSILON = np.power(10.0, -15)
    for indexBaseV in range(len(baseVectors)):
        for nextBaseV in range(indexBaseV + 1, len(baseVectors)):
            dot =  np.dot(baseVectors[indexBaseV], baseVectors[nextBaseV])
            assert abs(dot) <= EPSILON, "Vectors are not othogonal but %s instead" % dot
            
    baseVectors = np.array(baseVectors)
    
    assert np.allclose(baseVectors.T, nl.inv(baseVectors), atol=EPSILON), "The matrix produce is not orthonormal!"
    return baseVectors

In [8]:
baseV = buildOrthonormalMatrixBasedOn(vectors)
baseV

Shape  (3, 3)


array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.49206783,  0.63968818, -0.5904814 ],
       [ 0.82851716, -0.55234477,  0.09205746]])

Projection of vector to normalized vector is np.dot(V, e)

In [9]:
np.dot(baseV[0], baseV[1]) # The two base are orthogonal !

0.0

In [10]:
buildOrthonormalMatrixBasedOn(baseV)

Shape  (3, 3)


array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.49206783,  0.63968818, -0.5904814 ],
       [ 0.82851716, -0.55234477,  0.09205746]])