In [42]:
from math import sqrt
import numpy as np
import numpy.linalg as nl
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator(100))})

In [43]:
def pageRank(linkMatrix, d=0.5):
    linkMatrix = np.array(linkMatrix)
    n = linkMatrix.shape[0]
    M = d * linkMatrix + (1-d)/n * np.ones([n, n])
    r = 100 * np.ones(n) / n
    lastR = r
    r = M @ r
    i = 0
    while nl.norm(lastR - r) > 0.01 :
        lastR = r
        r = M @ r
        i += 1  
    return r

In [44]:
def getAll(matrix):
    matrix = np.array(matrix)
    vals, vecs = nl.eig(matrix)
    try:
        print ("Values: ")
        print (vals)
    except:
        pass
    try:
        print ("Vectors: ")
        print (vecs)
    except:
        pass

In [45]:
getAll([[4,-5,6], [7,-8,6], [3/2, -1/2, -2]])

Values: 
[1 -4 -3]
Vectors: 
[[-53/77 -2/3 20/49]
 [-53/77 -2/3 -20/49]
 [-14/61 1/3 -40/49]]


In [46]:
getAll([[0,0,0,1], [1,0,0,0], [0,1,0,0], [0,0,1,0]])

Values: 
Vectors: 


In [49]:
pageRank([[0,0,0,1], [1,0,0,0], [0,1,0,0], [0,0,1,0]])

array([25, 25, 25, 25])

In [47]:
getAll([
    [0.1,0.1,0.1,0.7], 
    [0.7,0.1,0.1,0.1], 
    [0.1,0.7,0.1,0.1], 
    [0.1,0.1,0.7,0.1]
])

Values: 
Vectors: 


In [48]:
pageRank([
    [0.1,0.1,0.1,0.7], 
    [0.7,0.1,0.1,0.1], 
    [0.1,0.7,0.1,0.1], 
    [0.1,0.1,0.7,0.1]
])

array([25, 25, 25, 25])

In [50]:
nl.det([[0,1,0,0],
       [1,0,0,0],
       [0,0,0,1],
       [0,0,1,0]
       ])

1.0

In [51]:
pageRank([[0,1,0,0],
       [1,0,0,0],
       [0,0,0,1],
       [0,0,1,0]
       ])

array([25, 25, 25, 25])

In [52]:
getAll([
   [3/2, -1],
    [-1/2, 1/2]
])

Values: 
[181/97 13/97]
Vectors: 
[[77/82 13/22]
 [-11/32 71/88]]
